# Generated by Django 5.2.4 on 2025-08-15 19:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashcontribution',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_activated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='charity',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_activated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='charityneed',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_activated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='charityneedmedia',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_activated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='charitytype',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_activated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contributionfulfillment',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_activated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='donationitemtype',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_activated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='goodscontribution',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_activated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='servicecontribution',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_activated', to=settings.AUTH_USER_MODEL),
        ),
    ]
