# Generated by Django 5.2.4 on 2025-08-15 19:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ayah',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_activated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ayahaudio',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_activated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ayahtafseer',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_activated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recitationtype',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_activated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reciter',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_activated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='surah',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_activated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='surahaudio',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_activated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='surahtafseer',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_activated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tafseersource',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_activated', to=settings.AUTH_USER_MODEL),
        ),
    ]
